FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app cmd/bot/main.go


FROM alpine:3.18
ENV NUMBER_OF_BOTS=9
WORKDIR /app
COPY --from=builder /app/app .
CMD ["./app"]
